name: uts_simulasi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.0
  shared_preferences: ^2.0.6
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.5
  sqflite: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
